PROGRAM_spu	:= mhd_spu

LIBRARY_embed	:= lib_mhd_spu.a 

INCLUDE		:= -I  .. 

IMPORTS		:= -lm

CC_OPT_LEVEL    = -O0 -g

ifdef CELL_TOP
        include $(CELL_TOP)/buildutils/make.footer
else
        include ../../../../../buildutils/make.footer
endif

